package com.project.cureconnect.presentation.navigationRoutes

sealed class Screen(val routes : String) {
    object SplashScreen : Screen("splash_screen")
    object WelcomeScreen1 : Screen("welcome_screen1")
    object WelcomeScreen2 : Screen("welcome_screen2")
    object WelcomeScreen3 : Screen("welcome_screen3")
    object Login : Screen("Log_in")
    object SignUp : Screen("sign_up")
    object createPost : Screen("create_post")
    object ForgotPassword : Screen("forgot_password")
    object MainDashBoard : Screen("main_dashboard")
    object Telemedicine : Screen("telemedicine")
    object Analysis : Screen("analysis")
    object HealthTips : Screen("health_tips")
    object Consult : Screen("consult")
    object Emergency : Screen("emergency")
    object Appointment : Screen("appointment")
    object Videobyutbe : Screen("videobyutbe")
    object home : Screen("home")
    object search : Screen("search")
    object profile : Screen("profile")
    object AvailabelDoctor : Screen("availble_doctor")
    object DoctorDashborad : Screen("doctor_dashborad")
    object chatScreen : Screen("chat_screen")
    object Navigation : Screen("navigation")
    object MyAppointment : Screen("my_appointment")
    object WelcomeScreenD1 : Screen("welcome_screen_d1")
    object WelcomeScreenD2 : Screen("welcome_screen_d2")
    object WelcomeScreenD3 : Screen("welcome_screen_d3")
}

